### DISCUSSION TITLE
Error: creating build container: short-name resolution enforced but cannot prompt without a TTY

### DISCUSSION THREAD

**Discussion by lmilbaum** [npalm/terraform-aws-gitlab-runner#955] [Q&A]
This is the job I'm running:
```
build-image:
  image: quay.io/buildah/stable:v1.31.0
  stage: build
  script: buildah bud --no-cache -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}" .
 ```

The parent image is hosted in quay.io. The short-name is used.

Would appreciate your advice
