### ISSUE TITLE
Runner configuration does not work with DinD 19.03+

### ISSUE THREAD

**Issue by Glen-Moonpig** [npalm/terraform-aws-gitlab-runner#160]
As of version 19.03, docker:dind will automatically generate TLS certificates in the directory specified by the DOCKER_TLS_CERTDIR environment variable and require using them for communication.

When you upgrade to 19.03 (which is done automatically if using docker:dind) you may start seeing an issue like:

> docker: Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?.

To fix the problem above you have two options:

- Configure GitLab Runner to use TLS.
- Explicitly turn off TLS.

Since the service docker:dind will create the certificates, we need to have the certificate shared between the service and the job container. To do this we have to add a mount inside of the volumes under the [runners.docker] section.

For example:

```
[[runners]]
  name = "My Docker Runner"
  url = "http://gitlab.com"
  token = ""
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    privileged = true
    volumes = ["/certs/client", "/cache"]
    shm_size = 0
```

Also, update .gitlab-ci.yml accordingly to specify the DOCKER_TLS_CERTDIR

```
image: docker:19.03.0

variables:
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.0-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t my-docker-image .
    - docker run my-docker-image /script/to/run/tests
```

**Comment by npalm** [comment]
I did a quick test, you can configure the runner so it will mount the cert dir so builds will work with docker:dind image as a service. Set the following property for the module 
```
  runners_additional_volumes = ["/certs/client"]
```

I have tested the configuration https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/examples/runner-default/main.tf with the following `.gitlab-ci.yml` It works as expected.
```
build:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull -t blurk .
    - docker run blurk
```
