### ISSUE TITLE
Support for Docker Hub registry mirror for rate-limited pulls

### ISSUE THREAD

**Issue by jessedobbelaere** [npalm/terraform-aws-gitlab-runner#270]
While running some automation jobs in bulk on my Gitlab projects, I got hit today by the infamous new [Docker Hub Rate Limiting](https://www.docker.com/increase-rate-limits)...

```
Waiting for services to be up and running...
Pulling docker image docker:latest ...
ERROR: Preparation failed: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit (docker.go:142:0s)
``` 

There are some solutions to this problem:
* **Authenticate to docker hub**. Anonymously you get 100 container image requests per 6 hours, with an authenticated account you get 200 container image requests per 6 hours. 
* **Pay for Docker Hub**. There's a [Pro account](https://www.docker.com/pricing) already for only $5/month. Requires you to authenticate. For a company, this is the easiest solution and makes the most sense to pay for such a critical service. In my case, it's a personal project for fun so worth looking for other (cheaper) ways. 
* **Cache on GitLab container registry**: tag and push the docker hub image you use (e.g. `php:8`) to your Gitlab repository container registry to "cache", and simply pull from that one to decrease pulls from docker hub. Bit tedious... 
* Use the free [**Gitlab Dependency Proxy**](https://docs.gitlab.com/ee/user/packages/dependency_proxy/) 
  * Requires you to add a `docker login` statement and to prefix every docker image with `$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX`. Currently, I tried this but get a 500 error back on `docker pull`...
* **Self-Hosted Docker Registry As Pull-Through Cache**:  [Docker Hub Registry Mirror](https://docs.gitlab.com/runner/configuration/speed_up_job_execution.html#docker-hub-registry-mirror) and let the runner use this as a registry as a pull-through cache. A similar thing can be done with JFrog Artifactory/Container Registry. Because distribution uses HEAD manifest requests to check if cached content has changed, it will not count towards the rate limit. Note that initial requests for Hub images that are not yet in cache will be counted.
* Google and AWS have both launched a solution: https://cloud.google.com/container-registry/docs/pulling-cached-images and https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/ and https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/

Does anyone have experience with any of these solutions? Did anyone try the self-hosted Docker registry mirror? Would it make sense to spin it up in this repo, or provide config options in this repo to add it?

**Comment by Nightbr** [comment]
Hey, 
it could be great to setup a Docker registry proxy and configure the runner to point on it. But sure +1 for this killer feature.

So far, I have my own workaround, I have a repository of all my base docker images (`my-org/docker-env`) and I use this simple `.gitlab-ci.yaml` script to build the images and publish them to the Gitlab registry.

```yaml
stages:
    - build

# Define variables
variables:
    CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

# Build docker image
build-image:
    stage: build
    image: docker:1.12-dind
    services:
        - docker:dind
    script:
        - cat /etc/resolv.conf
        - cat /etc/hosts
        - echo $CI_REGISTRY
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CONTAINER_IMAGE .
        - docker push $CONTAINER_IMAGE
 
```

I build one image per branch:

![image](https://user-images.githubusercontent.com/4228646/103525158-12e8ec80-4e7f-11eb-8252-113756d0720a.png)

And publish the branch name as a tag for the image repository registry.

Finally use my base images in my other projects in `.gitlab-ci.yml` or `Dockerfile`. 

For example:

`registry.gitlab.com/my-org/docker-env:node14-nx`


Source: https://about.gitlab.com/blog/2020/10/30/mitigating-the-impact-of-docker-hub-pull-requests-limits
