### ISSUE TITLE
dind docker builds: how to make it work like GitLab shared runners?

### ISSUE THREAD

**Issue by jrr** [npalm/terraform-aws-gitlab-runner#357]
We're using a runner based on the [runner-default](https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/examples/runner-default) example, and overall it's been great: we're able to run most* of our builds on it, and they run much faster than they did on the GitLab shared runners we were using before.

The jobs we're not yet running on the EC2 runner are those that perform Docker builds, using [dind](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-the-docker-image-docker-in-docker) like this:

```yaml
example-job:
  image: docker:20.10
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:20.10-dind
  script: |
    docker build (...)
```

These work on the shared runners, but fail on our EC2 runners with a message like this:

```
Cannot connect to the Docker daemon at tcp://docker:2375/. Is the docker daemon running?
```

Based on my current shaky understanding of the various pieces (this project, docker-machine, GitLab runners, etc.), I think the important question is: 

_How do I configure an AWS runner to be able to perform dind docker builds the same way as GitLab's runners?_

Would you expect the above job to work on a runner provisioned with the [runner-default example](https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/examples/runner-default/main.tf)? (if so, then I'll more closely diff my config against that) 

Do I need to set any specific [inputs](https://github.com/npalm/terraform-aws-gitlab-runner#inputs)?

Here's my current configuration:

<details>
<summary>main.tf</summary>

```tf
data "aws_availability_zones" "available" {
  state = "available"
}

data "aws_security_group" "default" {
  name   = "default"
  vpc_id = module.vpc.vpc_id
}
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.70"

  name = "vpc-${var.environment}"
  cidr = "10.0.0.0/16"

  azs             = [data.aws_availability_zones.available.names[0]]
  private_subnets = ["10.0.1.0/24"]
  public_subnets  = ["10.0.101.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true
  enable_s3_endpoint = true

  tags = {
    Environment = var.environment
  }
}
module "gitlab-runner" {
  # https://registry.terraform.io/modules/npalm/gitlab-runner/aws/
  source  = "npalm/gitlab-runner/aws"
  version = "4.27.0"

  aws_region  = var.aws_region
  environment = var.environment

  vpc_id                   = module.vpc.vpc_id
  subnet_ids_gitlab_runner = module.vpc.private_subnets
  subnet_id_runners        = element(module.vpc.private_subnets, 0)

  runners_name       = var.runner_name
  runners_gitlab_url = "https://gitlab.com"

  gitlab_runner_registration_config = {
    registration_token = var.registration_token
    tag_list           = var.tag_list
    description        = var.runner_description
    locked_to_project  = "true"
    run_untagged       = "false"
    maximum_timeout    = "3600"
  }

}

variable "registration_token" {
  description = "gitlab registration token"
  type        = string
}
variable "aws_region" {
  type = string
}

variable "environment" {
  description = "A name that identifies the environment, will used as prefix and for tagging."
  type        = string
  default     = "runners-default"
}

variable "runner_name" {
  description = "Name of the runner, will be used in the runner config.toml"
  type        = string
}

variable "runner_description" {
  description = "This description will appear in the GitLab runner list"
  type        = string
}

variable "tag_list" {
  description = "GitLab tags for this runner"
  type        = string
}
```

</details>

Hopefully I'm missing something obvious, but it might be worth calling out a section in the Readme for "here's how to make your runner support dind docker builds", perhaps with separate guidance for TLS and non-.

**Comment by keatmin** [comment]
Hey @jrr I faced the same thing and this [issue](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27300) solved it for me!

**Comment by jrr** [comment]
For anyone running across this, we've managed to get docker builds working on the EC2 agent, by adjusting the CI config to look like this:

```yml
services:
  # Configuration to support docker builds on custom EC2 runner from
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27300#note_571697847
  - name: docker:dind
    command: ["--tls=false"]
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
image: docker:20.10
script: |
  docker build (...)
```

But the issue's question remains: what would it take to not require the `--tls=false` and `DOCKER_TLS_CERTDIR` workarounds?
